imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@LibraryBundle/Resources/config/services.yml" }

parameters:
    default_timezone: Asia/Aqtau
    site_name: 'Book library'
    site_url: 'http://library.local'
    webmaster_email: web@library.local
    from_email: noresponse@library.local
    site_title: '<strong title="%s">Book Library</strong>'
    site_description: 'Electronic book storage'
    footer_text: '&copy; 2017 Book Library, <a class="text-gray" href="https://axisful.info">Igor Ivlev</a>'
    page_title_sfx: 'Book Library'


framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    form:
#        resources:
#            - 'LibraryBundle:Forms:media_widgets.html.twig'
    form_themes: 
        - 'bootstrap_3_layout.html.twig'
    globals:
        page_title_sfx: "%page_title_sfx%"
        footer_text: "%footer_text%"
        site_description: "%site_description%"
        site_title: "%site_title%"
        site_name: "%site_name%"
        site_url: "%site_url%"
        default_timezone: "%default_timezone%"
        webmaster_email: "%webmaster_email%"
        
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8        
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: /usr/bin/node
    filters:
        cssrewrite: ~
        uglifyjs:
            bin: /usr/bin/uglifyjs
            compress: true
            mangle: true
        uglifycss:
            bin: /usr/bin/uglifycss
    assets:
        common_js:
            inputs:
                - '@LibraryBundle/Resources/public/external/js/jquery/jquery-2.1.0.min.js'
#                - '@ArcelorBundle/Resources/public/external/kingadmin/assets/js/bootstrap/bootstrap.js'
#                - '@Library/Resources/public/js/app.js'
        common_css:
            inputs:
                - 'bundles/library/external/bootstrapped/vendor/bootstrap/css/bootstrap.min.css'
                - 'bundles/library/external/bootstrapped/css/4-col-portfolio.css'
                - 'bundles/library/css/library-style.css'


fos_user:
    db_driver:  orm
    #firewall_name:  main
    firewall_name:  secure_area
    user_class:  Application\Sonata\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation

    group:
        group_class:  Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager  

    service:
        user_manager: sonata.user.orm.user_manager  
        
    from_email:
        address:        "%webmaster_email%"
        sender_name:    "%site_name%"

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:  [admin]

        # used to display the menu in profile pages      
        sonata.user.block.menu:

        # used to display menu option (login option)
        sonata.user.block.account:

        # used to if you plan to use Sonata user routes
        sonata.block.service.text:

sonata_user:
    #security_acl: true # Uncomment for ACL support
    manager_type: orm
    admin:
        user:
            class: LibraryBundle\Admin\UserAdmin
           
    profile:
        # Profile show page is a dashboard as in SonataAdminBundle
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: ":)"} }

        # Customize user portal menu by setting links
        menu:
#            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit_authentication', label: 'link_edit_authentication', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'title_user_edit_password', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_show', label: 'title_user_complaints', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_show', label: 'title_user_comments', domain: 'SonataUserBundle'}
    
sonata_admin:
    title: Web Admin
    title_logo: /bundles/library/img/success-cat.jpg
    show_mosaic_button:   false
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout:                   LibraryBundle:SonataAdminBundle:standart_layout.html.twig
        user_block:               LibraryBundle:SonataAdminBundle:user_block.html.twig
        short_object_description: LibraryBundle:SonataAdminBundle:short-object-description.html.twig
        
    dashboard:
        blocks:
            - { position: left,  type: sonata.admin.block.admin_list, settings: { groups: [manage] } }
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [users] } }

        groups:
            manage:
                label: admin.title.manage
                items:
                    - library.admin.book
                    - library.admin.author
                    - {route: home , label: 'Main page'}
                roles: [ ROLE_ADMIN ]
            users:
                label: admin.title.users
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
#            media:
#                label: admin.title.media
#                items:
#                    - sonata.media.admin.media
#                    - sonata.media.admin.gallery
#                    #- sonata.media.admin.gallery_has_media
#                    - sonata.classification.admin.collection
#                    - sonata.classification.admin.context
#                    - sonata.classification.admin.tag


apy_data_grid:
    theme: '@LibraryBundle/APYDataGridBundle/blocks.html.twig'
    limits: 10
    persistence: true
    no_data_message: 'No data'
    no_result_message: 'No results'
    pagerfanta:
        enable: true    #default false
        view_class: Pagerfanta\View\TwitterBootstrap3View #default    Pagerfanta\View\DefaultView
        options:            #all options of pager fanta view constructor
           prev_message : «
           next_message : »
           css_container_class: "pagination"


#sonata_classification:
    #---
#
#sonata_media:
#    # if you don't use default namespace configuration
#    #class:
#    #    media: MyVendor\MediaBundle\Entity\Media
#    #    gallery: MyVendor\MediaBundle\Entity\Gallery
#    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
#    db_driver: doctrine_orm
#    default_context: complaints
#    providers:
#        image:
#            resizer: sonata.media.resizer.square
#    contexts:
#        default:  # the default context is mandatory
#            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
#                - sonata.media.provider.image
#                - sonata.media.provider.file
#                - sonata.media.provider.vimeo
#
#            formats:
#                small: { width: 100 , quality: 75}
#                big:   { width: 500 , quality: 75}
#
#        complaints:
#            providers:
#                - sonata.media.provider.image
#
#            formats:
#                small: { width: 245, height: 245, quality: 80}
#                preview: { width: 500, quality: 80}
#                large:   { width: 800, quality: 80}
#
#    cdn:
#        server:
#            path: /uploads/media
#
#    filesystem:
#        local:
#            directory:  "%kernel.root_dir%/../web/uploads/media"
#            create:     false