library:
    resource: "@LibraryBundle/Controller/"
    type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

# FOSUserBundle's routing   
#fos_user_security:
#  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#  prefix: /profile
#
#fos_user_register:
#  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#  prefix: /register
#
#fos_user_resetting:
#  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#  prefix: /resetting
#
#fos_user_change_password:
#  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#  prefix: /profile 
# app/config/routing.yml


# Sonata user
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
    prefix: /secure_area

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /secure_area/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /secure_area/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /secure_area/register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /secure_area/profile
    
# Admin's routing   
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting
    
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

# Media bundle
#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media
    
