<?php

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 */
class User extends BaseUser
{

    /**
     * @var int $id
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();

    }

}
